name: Full Crawl Weekly

on:
  schedule:
    # Run weekly on Sundays at 03:00 UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  full-crawl:
    runs-on: ubuntu-latest
    env:
      CRAWLER_BATCH_SIZE: 50
      CRAWLER_MAX_CONCURRENT: 5
      CRAWLER_DELAY: 0.5
      CRAWLER_MAX_RETRIES: 3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full crawl
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CORTICO_API_URL: ${{ vars.CORTICO_API_URL }}
        run: python main.py --mode full