name: Segment Coordinator

on:
  schedule:
    # Run after all segments are complete, Thursday at 03:00 UTC
    - cron: '0 3 * * 4'
  workflow_dispatch:

jobs:
  coordinate-segments:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run final coordination tasks
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "All segments completed. Running coordination tasks..."
          
          # Add any final coordination tasks here, such as:
          # 1. Database consistency checks
          # 2. Sending completion notifications
          # 3. Generating reports
          # 4. Cleanup tasks
          
          echo "Segment coordination completed successfully!"

      - name: Generate status report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Generating crawl status report..."
          python track_crawl_status.py --save --filename crawl_status_report.json

      - name: Upload status report
        uses: actions/upload-artifact@v3
        with:
          name: crawl-status-report
          path: crawl_status_report.json